# Welcome to Jekyll!

# Website settings
title: Bing
description: Bing's blog
keywords: Bing, UCF, Jekyll, github
baseurl: # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://bingrao.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: Bing
  public_key: e5tXhjmwy3ZNBE0KeMucnn49oUEzqBYZorZqvQnRx1Ha3K1vyXazCe5pHBeIPLK1

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-102762563-1

## google optimize
go:
  id: GTM-TNKSPW4


## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:


# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

incremental: BOOL

#permalink: /blog/:categories/:year/:month/:day/:title.html
permalink: /blog/post/:year/:month/:day/:title.html
